// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  name: __t.string(),
  isSun: __t.bool().name("is_sun"),
  orbitRadius: __t.f32().name("orbit_radius"),
  bodySize: __t.f32().name("body_size"),
  color: __t.string(),
  angle: __t.f32(),
  speed: __t.f32(),
  rotationAngle: __t.f32().name("rotation_angle"),
  rotationSpeed: __t.f32().name("rotation_speed"),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
