// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Pose,
} from "./types";


export default __t.row({
  identity: __t.identity().primaryKey(),
  mode: __t.string(),
  get playerPose() {
    return Pose.name("player_pose");
  },
  get shipPose() {
    return Pose.name("ship_pose");
  },
  speed: __t.f32(),
  grounded: __t.bool(),
  updatedAt: __t.timestamp().name("updated_at"),
});
