// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  bodyId: __t.u64().name("body_id"),
  seed: __t.u64(),
  planetType: __t.string().name("planet_type"),
  waterLevel: __t.f32().name("water_level"),
  terrainScale: __t.f32().name("terrain_scale"),
  colorA: __t.string().name("color_a"),
  colorB: __t.string().name("color_b"),
  atmosphereColor: __t.string().name("atmosphere_color"),
  atmosphereDensity: __t.f32().name("atmosphere_density"),
});
