// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CelestialBody = __t.object("CelestialBody", {
  id: __t.u64(),
  name: __t.string(),
  isSun: __t.bool(),
  orbitRadius: __t.f32(),
  bodySize: __t.f32(),
  color: __t.string(),
  angle: __t.f32(),
  speed: __t.f32(),
  rotationAngle: __t.f32(),
  rotationSpeed: __t.f32(),
  axialTilt: __t.f32(),
  orbitalInclination: __t.f32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
export type CelestialBody = __Infer<typeof CelestialBody>;

export const OrbitTick = __t.object("OrbitTick", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type OrbitTick = __Infer<typeof OrbitTick>;

export const PlanetParams = __t.object("PlanetParams", {
  id: __t.u64(),
  bodyId: __t.u64(),
  seed: __t.u64(),
  planetType: __t.string(),
  terrainScale: __t.f32(),
  colorA: __t.string(),
  colorB: __t.string(),
  atmosphereColor: __t.string(),
  atmosphereDensity: __t.f32(),
});
export type PlanetParams = __Infer<typeof PlanetParams>;

export const Player = __t.object("Player", {
  id: __t.u64(),
  identity: __t.identity(),
  name: __t.string(),
  connected: __t.bool(),
  lastSeen: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;
