// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CelestialBody = __t.object("CelestialBody", {
  id: __t.u64(),
  name: __t.string(),
  isSun: __t.bool(),
  orbitRadius: __t.f32(),
  bodySize: __t.f32(),
  color: __t.string(),
  angle: __t.f32(),
  speed: __t.f32(),
  rotationAngle: __t.f32(),
  rotationSpeed: __t.f32(),
  axialTilt: __t.f32(),
  orbitalInclination: __t.f32(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
});
export type CelestialBody = __Infer<typeof CelestialBody>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  channel: __t.string(),
  scope: __t.string(),
  senderIdentity: __t.identity(),
  senderName: __t.string(),
  body: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  sentAt: __t.timestamp(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const ExplorerState = __t.object("ExplorerState", {
  identity: __t.identity(),
  mode: __t.string(),
  get playerPose() {
    return Pose;
  },
  get shipPose() {
    return Pose;
  },
  speed: __t.f32(),
  grounded: __t.bool(),
  updatedAt: __t.timestamp(),
});
export type ExplorerState = __Infer<typeof ExplorerState>;

export const PlanetAppearance = __t.object("PlanetAppearance", {
  bodyId: __t.u64(),
  revision: __t.u32(),
  settingsJson: __t.string(),
});
export type PlanetAppearance = __Infer<typeof PlanetAppearance>;

export const PlanetParams = __t.object("PlanetParams", {
  id: __t.u64(),
  bodyId: __t.u64(),
  seed: __t.u64(),
  planetType: __t.string(),
  waterLevel: __t.f32(),
  terrainScale: __t.f32(),
  colorA: __t.string(),
  colorB: __t.string(),
  atmosphereColor: __t.string(),
  atmosphereDensity: __t.f32(),
});
export type PlanetParams = __Infer<typeof PlanetParams>;

export const Player = __t.object("Player", {
  id: __t.u64(),
  identity: __t.identity(),
  name: __t.string(),
  connected: __t.bool(),
  lastSeen: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Pose = __t.object("Pose", {
  frame: __t.string(),
  x: __t.f64(),
  y: __t.f64(),
  z: __t.f64(),
  qx: __t.f64(),
  qy: __t.f64(),
  qz: __t.f64(),
  qw: __t.f64(),
});
export type Pose = __Infer<typeof Pose>;

export const WorldClock = __t.object("WorldClock", {
  id: __t.u32(),
  epoch: __t.timestamp(),
});
export type WorldClock = __Infer<typeof WorldClock>;

